### PR TITLE
fstabs: Make sdcard1 mount properly

### PR DESCRIPTION
**Pull request by taalojarvi**

### CODE REVIEW

**Comment by pirej** [comment]
You think that this will solve mounting sdcard as ext4 ?

**Comment by taalojarvi** [comment]
Pretty sure.  
Here is my reference: It's the Fstabs from ViperOS ( which supports EXT4 sdcard1 )

http//paste.ubuntu.com/24963973/

**Comment by taalojarvi** [comment]
I checked EXT4 support in DirtyUnicorns 64 bit build by @ssawrav . 
I have modified the fstabs accordingly

Link to the fstabs:
https://paste.ubuntu.com/24988196/

**Comment by pirej** [comment]
Ok, thanks, ill give it a try.

**Pull request closed without merging**
